menu:
  我是: /about
  试炼之地: http://fehey.com/demos/
  hey-Audio: http://fehey.com/hey-Audio/
  简历: http://fehey.com/resume/
  myFriends: http://fehey.com/friends/
rss: /atom.xml
description:
social:
  weibo: http://weibo.com/u/3799576961?refer_flag=1001030102_&is_hot=1
  github: https://github.com/EryouHao
  stack_overflow:
  facebook:
  twitter:
  google_plus:

page_comment: true
logo: /images/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: hexohey

google_analytics: UA-78918255-1
baidu_tongji: 9cdad07c755fa23f6aced510c6760e87
favicon: /images/avatar-small.ico
